name: Deployment to Production Server

on:
  push:
    branches:
      - deployer

jobs:
  build-js-production:
    name: Build JavaScript/CSS for Production Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: NPM Build
        run: |
          npm install
          npm run build
      - name: Put build assets in Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: public
          retention-days: 3

  deploy-production:
    name: Deploy project to Production Server
    runs-on: ubuntu-latest
    needs: [ build-js-production ]
    steps:
      - uses: actions/checkout@v4
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Deploy to Production Server
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Production
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: php8.2 vendor/bin/dep deploy rekatrack --branch="deployer" -vv
